### ISSUE TITLE
Docker volume /var/lib/postgresql/data fails to mount correctly

### ISSUE THREAD

**Issue by ilekilek** [bacularis/bacularis-docker#1]
Concerns: bacularis-docker / Dockerfile-alpine.template
Commit: c577aff / Aug 18 

Looks as if /`var/lib/postgresql/data` does not mount correctly on the docker host machine. Symptoms are:

- corresponding volume on the host machine is empty while the /`var/lib/postgresql/data` inside the container features all the files and dirs one would expect in a data directory for PostgreSQL
- when running `docker inspect` on a running bacularis container, the path strings in the `Volumes` list section look strange:
`            "Volumes": {`
`                "/etc/bacula,": {},`
`                "/var/lib/bacula": {},`
`                "/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Config,": {},`
`                "/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Logs,": {},`
`                "/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Config,": {},`
`                "/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Logs]": {},`
`                "[/var/lib/postgresql/data,": {}`
`            },`

The final path string starts with a left square bracket, and the penultimate string ends with a right square bracket. Root cause is probably a comma missing between the 3rd and the 4th element of the `VOLUME` list in line 53 of the `Dockerfile-alpine.template`:
`VOLUME ["/var/lib/postgresql/data", "/etc/bacula", "/var/lib/bacula" "/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Config",`

**Comment by ganiuszka** [comment]
Hello ilekilek,

Thank you for your detailed bug report.

Yes, you are fully right about this missing comma. I added it and now the docker inspect shows volumes correctly.

I pushed latest images 1.1.1  (alpine and bullseye) with the fix to Docker Hub.

Thanks again.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
I am closing this ticket.
