### ISSUE TITLE
bacularis-standalone: BackupCatalog job fails as Before script is called with a wrong argument

### ISSUE THREAD

**Issue by kibeb** [bacularis/bacularis-docker#2]
Out-of-the-box job named BackupCatalog fails:

`build-3-16-x86_64-dir JobId 4: shell command: run BeforeJob "/etc/bacula/scripts/make_catalog_backup MyCatalog"`

Seems to me the cause is that make_catalog_backup should be called with the name of the database, instead of name of the catalog. After changing the `Runscript #1`, which is called before this backup, to `/etc/bacula/scripts/make_catalog_backup bacula`, the job started to work.

(I used image: bacularis/bacularis-standalone:latest downloaded from Docker Hub on 2022-11-30.)

Thanks.

**Comment by ganiuszka** [comment]
Hello kibeb,

Thank you for detailed bug report and for proposed solution.

Yes, you are right that there is a problem in the Bacula Director configuration and using db name in runscript solves the issue. This configuration comes from Bacula packages from the Alpine Linux repository.

I fixed it on the bacularis-docker level. The fix will be available from Bacularis 1.2.2.

If you would like to use the BackupCatalog job with 1.2.1, please try images built with Debian Bullseye (bacularis-standalone:1.2.1-bullseye) or please wait on 1.2.2.

Thanks again.

Best regards,
Marcin Haba (gani)
